### ISSUE TITLE
Select one category from blog

### ISSUE THREAD

**Issue by Gliba** [graker/blogarchive#2]
Is there a way to select only one category from blog, and display all posts from selected one?

**Comment by graker** [comment]
Not at the moment. It is planned though, to add "archives by category" feature. 
I'll update this issue as soon as the feature will be added.

**Comment by Gliba** [comment]
Okay. Thanks!

**Comment by graker** [comment]
I have added category parameter to the component, now you can get archives for one category only using category slug.

Also note that since today Blog Archive component parameters should contain values for year, month, day and category slug, instead of url param names as before. So instead of `"year"` provide `"{{ :year }}"` as it is done in other October plugins. I should have done it like this from beginning anyway.
